[tool.poetry]
name = "ProjectZero"
version = "0.1.0"
description = ""
authors = ["Roman <98953084+Rokuflam@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
Django = "^5.0"
djangorestframework = "^3.14"
drf-spectacular = "^0.27"
djangorestframework-simplejwt = "^5.3"
django-allauth = "^0.60"
psycopg2-binary = "^2.9"
gunicorn = "^21.2"
whitenoise = "^6.6"
pillow = "^10.2"

[tool.poetry.dev-dependencies]
flake8 = "^7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
