[tool.poetry]
name = "ProjectZero"
version = "0.1.0"
description = "Django skeleton with most useful functionalities for new projects."
authors = ["Roman <98953084+Rokuflam@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
Django = "^5.0"
djangorestframework = "^3.14"
drf-spectacular = "^0.27"
djangorestframework-simplejwt = "^5.3"
psycopg2-binary = "^2.9"
gunicorn = "^21.2"
whitenoise = "^6.6"
pillow = "^10.2"
sentry-sdk = {version = "^1.40", extras = ["django"]}

[tool.poetry.dev-dependencies]
pylint = "^3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
