version: "3.9"

services:
  app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../env_files/.env
    volumes:
      - ../backend:/usr/src/backend
      - dev-static-data:/vol/web
    depends_on:
      - db
      - redis

  db:
    image: postgres:16-alpine
    env_file:
      - ../env_files/.env
    volumes:
      - dev-db-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - dev-redis-data:/data

volumes:
  dev-db-data:
  dev-static-data:
  dev-redis-data:
