version: "3.9"

services:
  app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../env_files/.env
    volumes:
      - ../backend:/usr/src/backend
      - ../staticfiles:/vol/web/static
      - ../media:/vol/web/media
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    env_file:
      - ../env_files/.env
    volumes:
      - dev-db-data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ../nginx/dev:/etc/nginx/conf.d
      - dev-static-data:/vol/web
    depends_on:
      - app

volumes:
  dev-db-data:
