version: "3.9"

services:
  app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../env_files/.env
    volumes:
      - ../backend:/usr/src/backend
      - dev-static-data:/vol/web
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    env_file:
      - ../env_files/.env
    volumes:
      - dev-db-data:/var/lib/postgresql/data


volumes:
  dev-db-data:
  dev-static-data:
