version: "3.9"

services:
  app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../env_files/.env
    volumes:
      - ../backend:/usr/src/backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/dev:/etc/nginx/conf.d
      # - ../ssl:/etc/nginx/ssl only if you have certificate
    depends_on:
      - app
