version: "3.9"

services:
  app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../env_files/.env
    volumes:
      - ../backend:/usr/src/backend
      - dev-static-data:/vol/web
    environment:
      - DB_HOST=db
      - DB_NAME=dbname
      - DB_USER=rootuser
      - DB_PASS=changeme
      - DEBUG=1
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    env_file:
      - ../env_files/.env
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=rootuser
      - POSTGRES_PASSWORD=changeme

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ../nginx/dev:/etc/nginx/conf.d
    depends_on:
      - app

volumes:
  dev-db-data:
  dev-static-data:
