# deploy.tpl
name: Deploy to Development env

on:
  push:
    branches:
      - development

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: development

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts

      - name: Build, tag, and push image to ECR
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:${{ github.sha }} -f docker/Dockerfile .
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}

      - name: Deploy to EC2
        run: |
          ssh -T -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} << 'EOF'
            # Install git if not already installed
            sudo apt-get update && sudo apt-get install git -y  # Assuming Ubuntu; adjust for other distributions as necessary

            # Navigate to the project directory or clone if not present
            cd /home/${{ secrets.EC2_USER }}/
            if [ ! -d "ProjectZero" ]; then
              git clone git@github.com:Rokuflam/ProjectZero.git
            fi
            cd ProjectZero

            # Ensure you're on the development branch and sync with origin
            git checkout development
            git fetch origin development

            # Reset local changes to allow a clean pull
            git reset --hard origin/development
            git pull origin development

            # Navigate to the Docker directory and run docker-compose
            cd docker
            docker-compose -f docker-compose-local.yml pull
            docker-compose -f docker-compose-local.yml up -d
          EOF
